---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/linkerd2-cli version --client
    register: linkerd2_test_output
  - debug:
      msg: '{{ linkerd2_test_output.stdout }}'
