---
- name: Testing andrewrothstein.linkerd
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'linkerd2-cli version --client'
      ansible.builtin.command: /usr/local/bin/linkerd2-cli version --client
      changed_when: false
      register: linkerd2_test_output
    - name: Output of 'linkerd2-cli version --client'
      ansible.builtin.debug:
        msg: '{{ linkerd2_test_output.stdout }}'
