---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: downloading {{ linkerd_url }} to {{ linkerd_install_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ linkerd_url }}'
    dest: '{{ linkerd_install_exe }}'
    mode: 0755
    checksum: '{{ linkerd_checksum }}'
- name: linking {{ linkerd_link }} to {{ linkerd_install_exe }}
  become: true
  become_user: root
  file:
    src: '{{ linkerd_install_exe }}'
    dest: '{{ linkerd_link }}'
    state: link
